#!/usr/bin/python
#
# Copyright (c) 2012 Mikkel Schubert <MSchubert@snm.ku.dk>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
from __future__ import absolute_import

import os
import sys
import shutil
import inspect
import tempfile
import traceback

import pypeline.logger
import pypeline.ui as ui
from pypeline.node import Node
from pypeline.pipeline import Pypeline

# Test modules, see _collect_tests
import adapterremoval_test # pylint: disable=W0611
import bwa_test            # pylint: disable=W0611
import bowtie2_test        # pylint: disable=W0611
import picard_test         # pylint: disable=W0611


tempfile.tempdir = os.path.join(tempfile.gettempdir(), os.getlogin())


def _collect_tests():
    for (name, obj) in sorted(globals().items()):
        if inspect.ismodule(obj) and name.endswith("_test"):
            module = name
            for (name, obj) in sorted(inspect.getmembers(obj)):
                if inspect.isfunction(obj) and name.startswith("test_"):
                    yield module, obj


class Config: # pylint: disable=W0232
    temp_root    = tempfile.mkdtemp(prefix = "pypeline_func")
    jar_root     = "tests/links/jar_root"
    dependencies = Node(description = "DummyDependency")
    log_file     = None
    log_level    = "error"
    jre_options  = ()


def main(argv):
    ui.print_info("Running functional Node tests:")
    ui.print_info("  - Destination = %r ..." % Config.temp_root)
    ui.print_info()

    pypeline.logger.initialize(Config, "logfile_%i.txt")

    errors = False
    pipeline = Pypeline(Config)
    for (module, func) in _collect_tests():
        Config.destination = os.path.join(Config.temp_root, module)

        try:
            ui.print_info("Adding node '%s' ..." % func.__name__)
            node = func(Config)
            pipeline.add_nodes(node)
        except StandardError:
            ui.print_err(traceback.format_exc())
            errors = True

        for metanodes in node.dependencies:
            for subnode in metanodes.dependencies:
                if Config.dependencies not in subnode.dependencies:
                    raise RuntimeError("Node did not pass dependencies: %s\n%r vs %r" \
                                       % (subnode, subnode.dependencies, Config.dependencies))

    dry_run = "--dry-run" in argv
    if not dry_run:
        pipeline.run(dry_run = True, max_running = 2)

    if pipeline.run(dry_run = dry_run, max_running = 2, progress_ui = "progress"):
        # Everything went fine, so there's currently no need to save the output
        ui.print_info("No errors; cleaning up temporary files.")
        shutil.rmtree(Config.temp_root)
    else:
        ui.print_info("There were errors; temporary files not removed!")
        errors = True

    return (1 if errors else 0)



if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
