# -*- mode: Yaml; -*-
# Timestamp: 2013-10-16T20:55:09.754672
#
# Default options.
# Can also be specific for a set of samples, libraries, and lanes,
# by including the "Options" hierarchy at the same level as those
# samples, libraries, or lanes below. This does not include
# "Features", which may only be specific globally.
Options:
  # Sequencing platform, see SAM/BAM reference for valid values
  Platform: Illumina
  # Quality offset for Phred scores, either 33 (Sanger/Illumina 1.8+)
  # or 64 (Illumina 1.3+ / 1.5+). For Bowtie2 it is also possible to
  # specify 'Solexa', to handle reads on the Solexa scale. This is
  # used during adapter-trimming and sequence alignment
  QualityOffset: 33

  # Settings for trimming of reads, see AdapterRemoval man-page
#  AdapterRemoval:
     # Adapter sequences, set and uncomment to override defaults
#     --pcr1: ...
#     --pcr2: ...
     # Pipeline defaults that differ from AR defaults;
     # To override, change the value(s) and uncomment the line(s):
#     --mm: 3
#     --minlength: 25
     # Features enabled by default; uncomment to disable:
#     --collapse: no
#     --trimns: no
#     --trimqualities: no

  # Settings for aligners supported by the pipeline
  Aligners:
    # Choice of aligner software to use, either "BWA" or "Bowtie2"
    Program: BWA

    # Settings for mappings performed using BWA
    BWA:
      # Filter hits with a mapping quality (Phred) below this value
      MinQuality: 25
      # Filter reads that did not map to the reference sequence
      FilterUnmappedReads: yes
      # Should be disabled ("no") for aDNA alignments, as post-mortem
      # localizes to the seed region, which BWA expects to have few
      # errors (sets "-l"). See http://pmid.us/22574660
      UseSeed:    yes
      # Additional command-line options may be specified for the "aln"
      # call(s), as described below for Bowtie2 below.

    # Settings for mappings performed using Bowtie2
    Bowtie2:
      # Filter hits with a mapping quality (Phred) below this value
      MinQuality: 0
      # Filter reads that did not map to the reference sequence
      FilterUnmappedReads: yes
      # Examples of how to add additional command-line options
#      --trim5: 5
#      --trim3: 5
      # Note that the colon is required, even if no value is specified
      --very-sensitive:
      # Example of how to specify multiple values for an option
#      --rg:
#        - CN:SequencingCenterNameHere
#        - DS:DescriptionOfReadGroup

  # Mark / filter PCR duplicates. If set to 'filter', PCR duplicates
  # are removed from the output files; if set to 'mark', these are
  # flagged with bit 0x400; if set to 'no', the reads are assumed to
  # not have been amplified. Collapsed reads are filtered using the
  # command 'bam_rmdup_duplicates', while "normal" reads are filtered
  # using Picard MarkDuplicates.
  PCRDuplicates: filter

  # Carry out quality base re-scaling of libraries using mapDamage
  # This will be done using the options set for mapDamage below
  RescaleQualities: no

  # Command-line options for mapDamage; note that the long-form
  # options are expected; --length, not -l, etc. Uncomment the
  # "mapDamage" line adding command-line options below.
  mapDamage:
    # By default, the pipeline will downsample the input to 100k hits
    # when running mapDamage; remove to use all hits
    --downsample: 100000

  # Exclude a type of trimmed reads from alignment/analysis; possible
  # types reflect the output of AdapterRemoval
#  ExcludeReads:
#    - Single    # Single-ended reads / Orphaned paired-ended reads
#    - Paired    # Paired ended reads
#    - Collapsed # Overlapping paired-ended reads collapsed into a
                 # single sequence by AdapterRemoval
#    - CollapsedTruncated # Like 'Collapsed', except that the reads
                          # truncated due to the presence ambigious
                          # bases or low quality bases at termini.

  # Optional steps to perform during processing
  # To disable all features, replace with line "Features: []"
  Features:
#    - Raw BAM        # Generate BAM from the raw libraries (no indel realignment)
                     #   Location: {Destination}/{Target}.{Genome}.bam
    - Realigned BAM  # Generate indel-realigned BAM using the GATK Indel realigner
                     #   Location: {Destination}/{Target}.{Genome}.realigned.bam
    - mapDamage      # Generate mapDamage plot for each (unrealigned) library
                     #   Location: {Destination}/{Target}.{Genome}.mapDamage/{Library}/
    - Coverage       # Generate coverage information for the raw BAM (wo/ indel realignment)
                     #   Location: {Destination}/{Target}.{Genome}.coverage
    - Depths         # Generate histogram of number of sites with a given read-depth
                     #   Location: {Destination}/{Target}.{Genome}.depths
    - Summary        # Generate target summary (uses statistics from raw BAM)
                     #   Location: {Destination}/{Target}.summary
    - DuplicateHist  # Generate histogram of PCR duplicates, for use with PreSeq
                     #   Location: {Destination}/{Target}.{Genome}.duphist/{Library}/


# Map of prefixes by name, each having a Path key, which specifies the
# location of the BWA/Bowtie2 index, and optional label, and an option
# set of regions for which additional statistics are produced.
Prefixes:
  # Phytophthora infestans nuclear genome:
  # Name of the prefix; is used as part of the output filenames
  Pi_nucl:
    # Path to .fasta file containg a set of reference sequences.
    Path:  prefixes/Pi_nucl.fasta

    # Label for prefix: One of nuclear, mitochondrial, chloroplast,
    # plasmid, bacterial, or viral. Is used in the .summary files.
    Label: nuclear

  # Phytophthora infestans mitochondrial genome:
  # Name of the prefix; is used as part of the output filenames
  Pi_mito:
    # Path to .fasta file containg a set of reference sequences.
    Path:  prefixes/Pi_mito.fasta

    # Label for prefix: One of nuclear, mitochondrial, chloroplast,
    # plasmid, bacterial, or viral. Is used in the .summary files.
    Label: mitochondrial


################################################################################
################################################################################
## Yoshido et al. 2013

# http://www.ebi.ac.uk/ena/data/view/ERS241538
M-0182896:
  # Options that apply to all data in this target
  Options:
    AdapterRemoval:
      # Adapters that differ from AdapterRemoval defaults
      --pcr1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNNATCTCGTATGCCGTCTTCTGCTTG"
      --pcr2: "AATGATACGGCGACCACCGAGATCTACACNNNNNNNACACTCTTTCCCTACACGACGCTCTTCCGATCT"

  M-0182896:
    M-0182896_NO_UDG:
      # Options that apply only to library “M-0182896_NO_UDG”
      # The remaining libraries have been treated with UDG, which removes the
      # signature of post-mortem DNA damage.
      Options:
        # Rescale base qualities to account for post-mortem damage
        RescaleQualities: yes

        Aligners:
          BWA:
            # Disable seed for ancient DNA
            UseSeed: no

      ERR267888: "rawreads/M-0182896/ERR267888_{Pair}_*.fastq.gz"

    M-0182896_UDG:
      ERR267889: "rawreads/M-0182896/ERR267889_{Pair}_*.fastq.gz"

    M-0182896_UDGa:
      ERR267946: "rawreads/M-0182896/ERR267946_{Pair}_*.fastq.gz"

    M-0182896_UDGb:
      ERR267947: "rawreads/M-0182896/ERR267947_{Pair}_*.fastq.gz"

    M-0182896_UDGc:
      ERR267948: "rawreads/M-0182896/ERR267948_{Pair}_*.fastq.gz"


# http://www.ebi.ac.uk/ena/data/view/ERS226850
06_3928A:
  # Options that apply to all data in this target
  Options:
    AdapterRemoval:
      # Adapters that differ from AdapterRemoval defaults
      --pcr1: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG"

  06_3928A:
    06_3928A:
      ERR248815: "rawreads/06_3928A/ERR248815_{Pair}_*.fastq.gz"
      ERR248816: "rawreads/06_3928A/ERR248816_{Pair}_*.fastq.gz"
      ERR248817: "rawreads/06_3928A/ERR248817_{Pair}_*.fastq.gz"
      ERR248818: "rawreads/06_3928A/ERR248818_{Pair}_*.fastq.gz"
      ERR248819: "rawreads/06_3928A/ERR248819_{Pair}_*.fastq.gz"
      ERR248820: "rawreads/06_3928A/ERR248820_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226848
DDR7602:
  DDR7602:
    DDR7602:
      ERR248813: "rawreads/DDR7602/ERR248813_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226849
LBUS5:
  LBUS5:
    LBUS5:
      ERR248814: "rawreads/LBUS5/ERR248814_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226846
NL07434:
  # Options that apply to all data in this target
  Options:
    AdapterRemoval:
      # Adapters that differ from AdapterRemoval defaults
      --pcr1: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG"

  NL07434:
    NL07434:
      ERR248806: "rawreads/NL07434/ERR248806_{Pair}_*.fastq.gz"
      ERR248807: "rawreads/NL07434/ERR248807_{Pair}_*.fastq.gz"
      ERR248808: "rawreads/NL07434/ERR248808_{Pair}_*.fastq.gz"
      ERR248809: "rawreads/NL07434/ERR248809_{Pair}_*.fastq.gz"
      ERR248810: "rawreads/NL07434/ERR248810_{Pair}_*.fastq.gz"
      ERR248811: "rawreads/NL07434/ERR248811_{Pair}_*.fastq.gz"
      ERR248812: "rawreads/NL07434/ERR248812_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226844
P13527:
  P13527:
    P13527:
      ERR248791: "rawreads/P13527/ERR248791_{Pair}_*.fastq.gz"
      ERR248792: "rawreads/P13527/ERR248792_{Pair}_*.fastq.gz"
      ERR248793: "rawreads/P13527/ERR248793_{Pair}_*.fastq.gz"
      ERR248794: "rawreads/P13527/ERR248794_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226845
P13626:
  P13626:
    P13626:
      ERR248795: "rawreads/P13626/ERR248795_{Pair}_*.fastq.gz"
      ERR248796: "rawreads/P13626/ERR248796_{Pair}_*.fastq.gz"
      ERR248797: "rawreads/P13626/ERR248797_{Pair}_*.fastq.gz"
      ERR248798: "rawreads/P13626/ERR248798_{Pair}_*.fastq.gz"

# http://www.ebi.ac.uk/ena/data/view/ERS226847
P17777:
  # Options that apply to all data in this target
  Options:
    AdapterRemoval:
      # Adapters that differ from AdapterRemoval defaults
      --pcr1: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG"

  P17777:
    P17777:
      ERR248799: "rawreads/P17777/ERR248799_{Pair}_*.fastq.gz"
      ERR248800: "rawreads/P17777/ERR248800_{Pair}_*.fastq.gz"
      ERR248801: "rawreads/P17777/ERR248801_{Pair}_*.fastq.gz"
      ERR248802: "rawreads/P17777/ERR248802_{Pair}_*.fastq.gz"
      ERR248803: "rawreads/P17777/ERR248803_{Pair}_*.fastq.gz"
      ERR248804: "rawreads/P17777/ERR248804_{Pair}_*.fastq.gz"
      ERR248805: "rawreads/P17777/ERR248805_{Pair}_*.fastq.gz"


################################################################################
################################################################################
## Martin et al. 2013

# http://www.ebi.ac.uk/ena/data/view/ERS258003
Pi1845A:
  # Options that apply to all data in this target
  Options:
    # Rescale base qualities to account for post-mortem damage
    RescaleQualities: yes

    Aligners:
      BWA:
        # Disable seed for ancient DNA
        UseSeed: no

  Pi1845A:
    Pi1845A_id_CGCTAT:
      ERR299534: "rawreads/Pi1845A/ERR299534_*.fastq.gz"
      ERR299565: "rawreads/Pi1845A/ERR299565_{Pair}_*.fastq.gz"
      ERR299566: "rawreads/Pi1845A/ERR299566_{Pair}_*.fastq.gz"
      ERR299567: "rawreads/Pi1845A/ERR299567_{Pair}_*.fastq.gz"
      ERR299568: "rawreads/Pi1845A/ERR299568_{Pair}_*.fastq.gz"

    Pi1845A_id_CATAGA:
      ERR299535: "rawreads/Pi1845A/ERR299535_*.fastq.gz"
      ERR299536: "rawreads/Pi1845A/ERR299536_*.fastq.gz"
      ERR299537: "rawreads/Pi1845A/ERR299537_*.fastq.gz"
      ERR299538: "rawreads/Pi1845A/ERR299538_*.fastq.gz"


# http://www.ebi.ac.uk/ena/data/view/ERS258007
Pi1889:
  # Options that apply to all data in this target
  Options:
    # Rescale base qualities to account for post-mortem damage
    RescaleQualities: yes

    Aligners:
      BWA:
        # Disable seed for ancient DNA
        UseSeed: no

  Pi1889:
    Pi1889_id_TAGCTT:
      ERR299525: "rawreads/Pi1889/ERR299525_*.fastq.gz"
      ERR299528: "rawreads/Pi1889/ERR299528_*.fastq.gz"
      ERR299531: "rawreads/Pi1889/ERR299531_*.fastq.gz"
      ERR299559: "rawreads/Pi1889/ERR299559_{Pair}_*.fastq.gz"
      ERR299562: "rawreads/Pi1889/ERR299562_{Pair}_*.fastq.gz"

    Pi1889_id_GGCTAC:
      ERR299526: "rawreads/Pi1889/ERR299526_*.fastq.gz"
      ERR299529: "rawreads/Pi1889/ERR299529_*.fastq.gz"
      ERR299532: "rawreads/Pi1889/ERR299532_*.fastq.gz"
      ERR299560: "rawreads/Pi1889/ERR299560_{Pair}_*.fastq.gz"
      ERR299563: "rawreads/Pi1889/ERR299563_{Pair}_*.fastq.gz"

    Pi1889_id_CTTGTA:
      ERR299527: "rawreads/Pi1889/ERR299527_*.fastq.gz"
      ERR299530: "rawreads/Pi1889/ERR299530_*.fastq.gz"
      ERR299533: "rawreads/Pi1889/ERR299533_*.fastq.gz"
      ERR299561: "rawreads/Pi1889/ERR299561_{Pair}_*.fastq.gz"
      ERR299564: "rawreads/Pi1889/ERR299564_{Pair}_*.fastq.gz"

