name: pre-commit

on:
  pull_request:
  push:
    branches: [main, v1.4.x]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-slim

    env:
      SKIP: no-commit-to-branch

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: j178/prek-action/@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5
