name: tests

on:
  pull_request:
  push:
    branches: [master, v1.4.x]

permissions:
  contents: read

jobs:
  tests:
    name: test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
      # Do not auto-cancel other runners if one fails
      fail-fast: false

    steps:
      - name: Audit all outbound calls
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "latest"
          enable-cache: true

      - name: nox (tests)
        run: uv run --with nox nox -s full_tests
